name: Build and Security Scan

on: [push, pull_request]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python/R environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Update pip
      run: pip install --upgrade pip
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Static Code Analysis with SonarQube
      uses: SonarSource/sonarcloud-github-action@master
      env:
         GIT_TOKEN: ${{ secrets.GIT_TOKEN }}  # Provided by GitHub
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Set in your repository secrets
      with:
       args: >
          -Dsonar.projectKey=SimplePython
          -Dsonar.organization=preddykolan19


    - name: Build and Test Python
      env:
        NUM1: '1.5'
        NUM2: '2.5'
      run: |
        python Simple.py install
        python -m unittest discover

    - name: Run CVE Scanning with Grype
      run: |
        docker run --rm -v ${{github.workspace}}:/src anchore/grype /src -o json > grype-output.json
        if grep -q '"severity":"Critical"' grype-output.json; then
          echo "Critical vulnerabilities found!"
         exit 1
        fi

    - name: Generate SBOM with Syft
      run: docker run --rm -v ${{github.workspace}}:/src anchore/syft /src -o json > sbom.json

    - name: Upload SBOM
      uses: actions/upload-artifact@v2
      with:
        name: sbom
        path: sbom.json
